import type { Metadata } from "next";
import "./globals.css";
import ProtectedRoute from "./component/ProtectedRoute";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <ProtectedRoute> */}
          {children}
        {/* </ProtectedRoute> */}
      </body>
    </html>
  );
}
