import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import Footer from "../component/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins", // Define CSS variable
});

export default function SignInLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}>
        <section id="Home" className="relative min-h-screen overflow-hidden">
        <div className="absolute inset-0">
            <Image 
            src="/astra.jpeg" 
            layout="fill" 
            objectFit="cover" 
            alt="Background Image"
            />
        </div>

        <div className="absolute inset-0 bg-[#202B51] to-transparent opacity-60 z-5"></div>

        {children}
        <div className="z-10">
            <Footer />
        </div>
        </section>
        
      </body>
    </html>
  );
}
